name: Retag

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker run --rm -v /tmp:/home/nonroot/.docker -t gcr.io/go-containerregistry/crane auth login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}" docker.io

      - name: Retag to git tag
        run: docker run --rm -v /tmp:/home/nonroot/.docker -t gcr.io/go-containerregistry/crane cp dex4er/debian-asdf:sha-${{ github.sha::7 }} dex4er/debian-asdf:${{ github.ref_name }}

      - name: Retag to latest
        run: docker run --rm -v /tmp:/home/nonroot/.docker -t gcr.io/go-containerregistry/crane cp dex4er/debian-asdf:sha-${{ github.sha::7 }} dex4er/debian-asdf:latest
